# Site
name: "Sean Rioux"
description: "I'm a web entrepreneur, programmer, and advocate. I believe in the social potential of a more open and humane world wide web."
baseurl: ""
include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-datapage-generator
  - jekyll-sitemap

# Page Gen
# https://github.com/avillafiorita/jekyll-datapage_gen

page_gen:
  - data: categories
    template: category
    name: key
    dir: category

# Site map
url: "https://seanrioux.com"

# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      permalink: /article/:name

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude:
  [
    README.markdown,
    package.json,
    grunt.js,
    Gruntfile.js,
    Gruntfile.coffee,
    node_modules,
  ]
